### ISSUE TITLE
SyntaxErrors when parsing MDX

### ISSUE THREAD

**Issue by narwold** [ChristopherBiscardi/gatsby-mdx#283] opened 2019-02-01 05:43 UTC
I'm trying to set up gatsby-mdx for the first time and am getting a TON of these:

```
SyntaxError: unknown: Expected corresponding JSX closing tag for <BR> (17:293)
```

...and these...

```
SyntaxError: unknown: Expected corresponding JSX closing tag for <MDXTag> (53:377)
```

Any suggestions?

**Comment by ChristopherBiscardi** [comment] 2019-02-01 05:44
looks like you're not closing your `<br/>` elements.

**Comment by narwold** [comment] 2019-02-01 05:50
They're not mine though. It almost looks like MDX is putting them in. MDXTag is obviously an MDX thing.

**Comment by narwold** [comment] 2019-02-01 05:51
Scratch that. It might be complaining about MDXTag because of the BRs. Not sure where the BRs are coming from, but let me do some looking around.

**Comment by ChristopherBiscardi** [comment] 2019-02-01 06:20
I'd check any AST manipulating plugins you might have configured. Their assumption could be that they're injecting HTML instead of JSX

**Comment by mgrubinger** [comment] 2019-02-10 19:28
I got similar errors, which is especially annoying b/c `gatsby develop` crashes afterwards. 
For me it helped to remove excess empty lines in my mdx files.

**Comment by jschuler** [comment] 2019-02-12 15:29
Got these as well, documented my issue in #288 . In my case, gatsby-transformer-react-docgen is parsing comments and creating markdown nodes which are then picked up by gatsby-mdx. If one such comment contains an unclosed tag it throws an error

**Comment by ChristopherBiscardi** [comment] 2019-02-12 20:43
for posterity: #288 is an issue with input that isn't intended to be compatible with markdown syntax, so is not related to the AST plugin issues here

**Comment by ChristopherBiscardi** [comment] 2019-02-28 21:48
closing since this has gone a month with no reproduction I can use to fix any specific issues

**Closed by ChristopherBiscardi** 2019-02-28 21:48 UTC
