### ISSUE TITLE
Error when trying to render multiple MDX pages: `ReferenceError: Can't find variable: React`

### ISSUE THREAD

**Issue by maxdesiatov** [ChristopherBiscardi/gatsby-mdx#162] opened 2018-10-01 14:12 UTC
**Describe the bug**
When trying to render MDX pages on another page (say on an index page) with `MDXRenderer` component, the project builds correctly, but an error is displayed when navigating to the development server at `http://localhost:8000`.

**To Reproduce**
1. Clone https://github.com/maxdesiatov/mdx-test, the repository is a default Gatsby starter with `gatsby-mdx` v0.1.4 dependency, a single `test.mdx` page and an `index.js` page that loads all available MDX pages with a GraphQL query:

```jsx
import MDXRenderer from 'gatsby-mdx/mdx-renderer';

export const pageQuery = graphql`
  query BasicWithQuery {
    allMdx {
      edges {
        node {
          id
          code {
            body
          }
        }
      }
    }
  }
`

export default function({ __mdxScope, data: {allMdx: {edges}} }) {
  return edges.map(({node: {id, code}}) => 
        <MDXRenderer key={id} scope={__mdxScope}>{code.body}</MDXRenderer>);
}
```

2. Run `yarn install`
3. Run `yarn run develop`
4. A few warnings are produced during the build process, not sure if these might be related:

```
warning Using the global `graphql` tag is deprecated, and will not be supported in v3.
Import it instead like:  import { graphql } from 'gatsby' in file:
/Users/maxd/Documents/mdx-test/src/pages/index.js
success extract queries from components — 0.057 s
success run graphql queries — 0.043 s — 6/6 139.69 queries/second
success write out page data — 0.004 s
success write out redirect data — 0.001 s
⢀ onPostBootstrapdone generating icons for manifest
success onPostBootstrap — 0.276 s

info bootstrap finished - 2.445 s

 WARNING  Compiled with 2 warnings                                                                                                                                                                     3:03:48 PM

 warning  in ./node_modules/React/cjs/react.development.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/maxd/Documents/mdx-test/node_modules/React/cjs/react.development.js
    Used by 1 module(s), i. e.
    /Users/maxd/Documents/mdx-test/node_modules/React/index.js
* /Users/maxd/Documents/mdx-test/node_modules/react/cjs/react.development.js
    Used by 1 module(s), i. e.
    /Users/maxd/Documents/mdx-test/node_modules/react/index.js

 warning  in ./node_modules/React/index.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /Users/maxd/Documents/mdx-test/node_modules/React/index.js
    Used by 3 module(s), i. e.
    /Users/maxd/Documents/mdx-test/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/Users/maxd/Documents/mdx-test/src/components/test.js
* /Users/maxd/Documents/mdx-test/node_modules/react/index.js
    Used by 124 module(s), i. e.
    /Users/maxd/Documents/mdx-test/node_modules/react-hot-loader/dist/react-hot-loader.development.js
```

5. Navigating to the development server shows a blank page with these errors in the browser console:

<img width="956" alt="screen shot 2018-10-01 at 15 05 37" src="https://user-images.githubusercontent.com/112310/46293659-0c76b680-c58c-11e8-8119-240f09f2caa0.png">

**Expected behavior**
Either an error is displayed that this GraphQL query or component usage are not permitted, or everything is built and rendered correctly.

**Comment by ChristopherBiscardi** [comment] 2018-10-01 14:50
Basically the issue is that MDX needs the scope (where scope is roughly "a collection of variables the mdx uses"). You can prime the scope yourself by manually passing the relevant variables (like in this example) but this requires you to already know what components are going to be used in your MDX file.

```js
import React from 'react'
import { MDXTag } from '@mdx-js/tag'
import BoldItalic from '../components/test'
import MDXRenderer from 'gatsby-mdx/mdx-renderer'

export const pageQuery = graphql`
  query BasicWithQuery {
    allMdx {
      edges {
        node {
          id
          code {
            body
          }
        }
      }
    }
  }
`

export default function({
  data: {
    allMdx: { edges },
  },
}) {
  return edges.map(({ node: { id, code } }) => (
    <MDXRenderer key={id} scope={{ React, MDXTag, BoldItalic }}>
      {code.body}
    </MDXRenderer>
  ))
}
```

---

We're working on automating the injection of the __mdxScope calculated from the MDX file for raw pageQueries, but today if you want to be able to use "any import" without thinking about it the page has to be generated via a createPage call, as shown in the [kitchen sink gatsby-node](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/38b82b80218977d20860f75ed8c1382dd0a05c10/examples/kitchen-sink/gatsby-node.js#L55-L64)

---

The warnings are unrelated. Somehow you seem to have a `React` and `react` folder in node_modules, which on a case-insensitive filesystem wouldn't be different folders and is why you see the warning.

**Comment by maxdesiatov** [comment] 2018-10-01 14:59
Not sure about FS case-sensitivity, as mine is case-insensitive. Anyway, many thanks for clarifying, would merging #123 have any impact on this?

**Comment by ChristopherBiscardi** [comment] 2018-10-01 15:07
#123 can't be merged as-is. It has to be taken apart and merged piece by piece, but yeah some of the ideas and code there will help as they're developed and merged over time.

**Closed by ChristopherBiscardi** 2018-10-01 15:07 UTC
