### ISSUE TITLE
Can't mix gatsby-remark-embed-video with gatsby-remark-responsive-iframe to get responsive iframe.

### ISSUE THREAD

**Issue by nestarz** [ChristopherBiscardi/gatsby-mdx#183] opened 2018-10-22 23:05 UTC
**Describe the bug**
Can't mix gatsby-remark-embed-video with gatsby-remark-responsive-iframe to get responsive iframe.

**To Reproduce**
```
...
    {
      resolve: 'gatsby-mdx',
      options: {
        extensions: [".mdx", ".md"],
        gatsbyRemarkPlugins: [
          {
            resolve: "gatsby-remark-embed-video",
            options: {
              width: 800,
              ratio: 1.77, // Optional: Defaults to 16/9 = 1.77
              // height: 400, // Optional: Overrides optional.ratio
              related: false, //Optional: Will remove related videos from the end of an embedded YouTube video.
              noIframeBorder: true //Optional: Disable insertion of <style> border: 0
            }
          },
          {
            resolve: "gatsby-remark-responsive-iframe",
            options: {}
          },
        ]
      }
    },
...
```

**Expected behavior**
Responsive iframe when using 
``video: https://www.youtube.com/watch?v=tkbU1bGOzWM`
inside a mdx file.
`

**Comment by ChristopherBiscardi** [comment] 2018-12-13 04:09
It doesn't look like the code you provided is valid for gatsby-remark-responsive-iframe, which requires you to type out an actual full iframe tag `<iframe url="http://www.example.com/" width="600" height="400"></iframe>`. If you're expecting these two plugins to automatically combine, I don't think they do right now because of the way embed-video inserts raw HTML instead of HAST or something responsive-iframe could process.

going to close this for now, but if this is indeed an MDX issue and it works with the remark transformer I'm happy to reopen.

**Comment by ar-stackrox** [comment] 2018-12-19 04:51
hey @ChristopherBiscardi I am also experiencing this issue with gatsby-mdx. I tried just running the plugins one at a time as well, and it does not render the iframe or the youtube video. I used just the <iframe> tag and I also tried the video markdown tag, and both render an empty div.

Have you successfully gotten either of these to work with gatsby-mdx? Also, to nestarz' comment, there does seem to be some synergy between the two according to the readme of Gatsby-remark-embed video, but I'd be happy with just getting these plugins to work individually first.


![image](https://user-images.githubusercontent.com/28272783/50199588-9ec66500-0306-11e9-82b7-706942eb9634.png)

**Comment by ar-stackrox** [comment] 2018-12-19 05:02
Oh, correction -- gatsby-remark-embed-video does work if you disable the gatsby-remark-responsive-iframe.

I can't get that plugin to work however (even with disabling embed-video)

**Comment by alisonjoseph** [comment] 2019-01-08 11:44
Seeing this same issue when trying to switch to mdx. gatsby-remark-responsive-iframe just renders an empty div for me too.

**Comment by alisonjoseph** [comment] 2019-01-09 00:17
Error reproduced here https://github.com/alisonjoseph/gatsby-mdx-minimal-repro

**Comment by ChristopherBiscardi** [comment] 2019-01-09 02:47
Thanks! I'm seeing this result after getting everything up to date there. gatsby-mdx 0.3.3, etc.

```
Iframe shortcode

`vimeo: https://vimeo.com/5299404`
```

![image](https://user-images.githubusercontent.com/551247/50873608-84b3fb80-1375-11e9-8205-b25ab56c5144.png)

I'll play around and see if I can figure out what's up. In the meantime you could consider using a different approach like `globalScope` and a react component: https://www.npmjs.com/package/react-vimeo

**Comment by alisonjoseph** [comment] 2019-02-19 18:44
Any update on this or should I just swap video's everywhere to a React component? 😸

**Comment by ChristopherBiscardi** [comment] 2019-02-19 22:48
It looks like a bug in the interaction between gatsby's special form of remark plugin and MDX. The AST from the plugins doesn't look like it gets injected properly even though it is processed.

I'd suggest moving to components if you can in general, especially for these sorts of plugins which are effectively encapsulated by a React component. If you can't move to a component, then let me know and I'll bump the priority of trying to get this fixed.

**Comment by alisonjoseph** [comment] 2019-02-19 22:57
@ChristopherBiscardi  I was able to easily update to a component 😄 thanks for looking into it!

**Comment by johno** [comment] 2019-03-13 00:08
This bug ultimately deals with a handful of plugins doing whacky things with HAST nodes while still in the MDAST so it's an upstream fix. Tomorrow I will begin work on patching those to work more reliably and then they will automatically work in gatsby-mdx since we're already coercing raw HTML into JSX during build.

**Comment by johno** [comment] 2019-04-16 20:46
This is now fixed. If you come across this issue please make sure your dependencies are up to date! ❤️

**Closed by johno** 2019-04-16 20:46 UTC
Labels: bug-upstream
