### ISSUE TITLE
Import a relative file inside a MDX file

### ISSUE THREAD

**Issue by nestarz** [ChristopherBiscardi/gatsby-mdx#199] opened 2018-12-05 13:19 UTC
Hello,

I would like to import a relative json file into my MDX (my json file is located in the same folder as my mdx file): 

`
import jsonFile from './jsonfile.json'
`

But it is not working, is there any other way do to it ?

Also, is it possible to import a relative JSX file inside my MDX file (same as my JSON, they are in the same folder) ?

**Comment by ChristopherBiscardi** [comment] 2018-12-06 01:52
How are you using MDX? relative imports should work if you're using the default `src/pages` support, but it doesn't work if you're using `createPages` because the MDX content can be coming from a remote source like Contentful. (technically it works from a remote source too, but you have to know the path from the .cache and we don't support depending on that path.

The easiest solution that always works in both cases is to use a small webpack config like this:

```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"]
    }
  });
};
```

then import from any folder in src/ such as:

```js
import Thing from 'components/thing/whatever.js';
```

If you prefer, you can extend this config to a more advanced use case, but this basic solution works.

**Comment by danoc** [comment] 2018-12-08 22:17
That worked well for my case.

If anyone can't get that to work, make sure that your imports are:

```js
import Thing from 'components/thing/whatever.js';
```

And not:

```js
import Thing from './components/thing/whatever.js';
``` 

Spent a few hours on Friday learning this the hard way. 😅

**Comment by aptfx** [comment] 2018-12-09 13:49
I've been hit by this too. We use Mdx and Gatsby to document source files. It is quite cumbersome to always have to denote absolute paths to the sibling javascript files we document. I fixed this in our lokal fork so that we rewrite the relative paths of the imports in the Mdx to absolute paths.

**Comment by ChristopherBiscardi** [comment] 2018-12-09 20:50
@aptfx The solution is to rewrite relative paths to account for the location of the cache automatically inside of the library, not make it configurable. I'd be happy to review a PR if you wanted to write one.

**Comment by aptfx** [comment] 2018-12-09 21:10
@ChristopherBiscardi But wouldn't the relative addressed JavaScript modules then live in remote sources (e.g. contentful)?

**Comment by ChristopherBiscardi** [comment] 2018-12-09 22:18
Relative imports are not supported in remote data sources (they don't make sense. What would it be relative to if the content is in a database?), so we could warn/fail if we find one by traversing up the node and checking to see if there's a parent, etc (it's a bit more complicated than that I think but we could do it). I'm less concerned about that though because when using a remote CMS for MDX content, few people think to use relative imports so I anticipate few people will run into the problem. I'm more concerned about supporting relative imports for gatsby-source-filesystem based MDX content. We have access to the filepath when we transform the MDX, so should be able to write a small babel plugin to rewrite the relative imports using node's path module, etc.

**Comment by ChristopherBiscardi** [comment] 2018-12-13 04:13
Also this is a dupe of #133, so closing this in favor of the earlier one.

**Closed by ChristopherBiscardi** 2018-12-13 04:13 UTC

**Comment by raphadeluca** [comment] 2019-02-15 14:08
When adding the webpack config in an existing project, switching from absolute paths to relative paths, it will throw errors, based on the olders paths still present in the cache.
Solution: delete the cache.
