### ISSUE TITLE
Gatsby-remark-images not working. 

### ISSUE THREAD

**Issue by mckeever02** [ChristopherBiscardi/gatsby-mdx#346] opened 2019-04-05 17:10 UTC
At a loss here as to what is wrong but I can't seem to get `gatsby-remark-images` working as a sub-plugin for `gatsby-mdx`. It was working fine with `gatsby-transformer-remark` before I converted over to mdx.

[gatsby-config.js](https://github.com/mckeever02/tryingtoworkv2/blob/master/gatsby-config.js):
```
{
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-mdx`,
      options: {
        extensions: ['.mdx', '.md'],
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
              sizeByPixelDensity: true,
              withWebp: true
            }
          }
        ]
      }
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
``` 

[blog/post/index.mdx](https://github.com/mckeever02/tryingtoworkv2/blob/master/blog/best-places-to-work-online-belfast/index.mdx):
```
![Guilt Trip Coffee + Donuts](./guilt-trip-interior.jpg)
```

The output is just: `<img src="./guilt-trip-interior.jpg" alt="Guilt Trip Coffee + Donuts">` which obviously isn't right. 

Any ideas why it isn't working?[ Link to the repo](https://github.com/mckeever02/tryingtoworkv2) if that helps.

 And [here's the blog page on netlify](https://tryingtowork.netlify.com/blog/best-places-to-work-online-belfast/). Featured images defined in frontmatter are being transformed just fine with sharp but as you can see, any images in the markdown aren't being transformed. 

Thanks

**Comment by mjhale** [comment] 2019-04-06 18:26
I'm experiencing a similar issue. It looks like the image files aren't being passed to gatsby-remark-images on initial page creation. However, it works as intended if any modification is made to the .mdx file while the development server is running.

I created a [minimal reproduction](https://github.com/mjhale/gatsby-mdx-image-issue) a few days ago to help pin down the problem. The page is generated via createPage() in gatsby-node.js. The mdx file is located at 'content/example/example.mdx' and can be accessed at '/example'.

**Comment by erikdstock** [comment] 2019-04-06 22:01
Same issue here, can confirm @mjhale's experience.

**Comment by erikdstock** [comment] 2019-04-06 22:31
I realized that in upgrading dependencies from `^0.4.x` i landed on the last 0.4 version. Upgraded to the latest (0.5.6), which also required a few more changes (changed name of package and some release candidates), but the issue persists.
![image](https://user-images.githubusercontent.com/9088720/55675986-545afb00-5899-11e9-90a5-71d4857190a6.png)

I double checked and my `gatsby-remark-images` and `gatsby-remark-relative-images` are unchanged.

**Comment by ChristopherBiscardi** [comment] 2019-04-06 22:57
I believe this has to do with the fact that the `File` nodes for the images are created *after* the `Mdx` nodes and since gatsby-remark-images is the one doing queries on the `File` nodes, the `Mdx` processing doesn't get re-triggered.

@johno might have more context.

**Comment by mckeever02** [comment] 2019-04-08 08:58
Not sure if my issue is related to @mjhale or @erikdstock as in my case, gatsby-remark-images isn't doing anything, whether dev server is running or not.

**Comment by wesbos** [comment] 2019-04-08 13:33
@johno Found a race condition related to this: https://twitter.com/wesbos/status/1113470306344210432

Talked to him on Discord and he said a fix is incoming :)

**Comment by sulco** [comment] 2019-04-12 18:17
Man, I spent about 3 hours today trying to debug/fix this issue - and also a couple a few days ago. Then I've figured "let's see, maaaybe there's an update".

`0.6.2` was published **2 hours ago**. And it does fix the issue 🥴

**Comment by ChristopherBiscardi** [comment] 2019-04-12 19:16
@sulco 😬 yes the issue is indeed fixed in the 0.6 branch. I hadn't gotten around to closing the issues yet.

The fix is in https://github.com/ChristopherBiscardi/gatsby-mdx/commit/0755e36c19c8839de918d722d4fd89e9a0526a89 and the problem was that we were caching the MDX calls in onCreateNode (where the plugins haven't been initialized yet).

**Closed by ChristopherBiscardi** 2019-04-12 19:16 UTC
Labels: bug

**Comment by itwasmattgregg** [comment] 2019-05-09 17:53
This fix appears to have broken relative images being referenced in frontmatter.
I get this error in my graphQL now: `Field "featuredImage" must not have a selection since type "String" has no subfields.`

For some reason it's not parsing relative image paths in frontmatter as gatsby image types post 0.6.1

Here's my query:
```
      frontmatter {
        title
        tags
        date(formatString: "MMMM DD, YYYY")
        featuredImage {
          childImageSharp {
            fluid(maxWidth: 4160) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
```

here's the mdx frontmatter piece:
```
featuredImage: './charles-koh-550122-unsplash.jpg'
```

**Comment by skipjack** [comment] 2019-09-06 10:40
I ran into this with `gatsby-plugin-mdx` simply because I didn't include the following `gatsby-source-filesystem` bit:

``` js
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: `${__dirname}/src/images`
      }
    },
```

Just sharing in case others have a similar issue. I think gatsby includes that by default but some it's easy to remove without realizing other plugins depend on it.
