### ISSUE TITLE
Custom Components provided via Webpack and/or MDXProvider can't be called from .mdx files

### ISSUE THREAD

**Issue by jonnybot0** [ChristopherBiscardi/gatsby-mdx#267] opened 2019-01-22 18:05 UTC
**Describe the bug**
If you define a custom component, you can't use it inside a .mdx file as I would expect.

This may be a regression or edge case of https://github.com/ChristopherBiscardi/gatsby-mdx/issues/59 ?

**To Reproduce**

Short version:
My example repo: https://github.com/jonnybot0/gatsby-mdx-broken-custom-components

After cloning & `yarn`, run `yarn develop`. Visit http://localhost:8000/demo-01.

Long version:
Basically, I just forked https://github.com/eggheadio/gatsby-starter-egghead-blog and added [a custom component](https://github.com/jonnybot0/gatsby-mdx-broken-custom-components/blob/master/src/components/SomeComponentOfMine.js), adding it to the MDXProvider used in the layout, then tried [using it inside one of the mdx files](https://github.com/jonnybot0/gatsby-mdx-broken-custom-components/blob/master/content/blog/demo01/index.md) that are created via the createPages API. 

When I run `gatsby develop` I get "ReferenceError: SomeComponentOfMine is not defined" at http://localhost:8000/demo-01. The actual develop build passes without errors, but the page won't load.

Looking at the generated code in .cache/gatsby-mdx/mdx-scopes-dir/, I can see that my custom component is actually getting imported into the scope okay:

```
import { SomeComponentOfMine } from "SomeComponentOfMine";
import React from 'react';
import { MDXTag } from '@mdx-js/tag';
export default {
  SomeComponentOfMine,
  React,
  MDXTag
};
```

So why can't it be found when I load up the page?

**Comment by snawbel** [comment] 2019-01-22 18:45
I'm having the same issue.

**Comment by ChristopherBiscardi** [comment] 2019-01-22 19:19
@jonnybot0 Can you delete `.cache` and see if that fixes the issue? (@snawbel can you try the same?)

The component renders for when I pull your repo and install from scratch, so I assume there's a caching issue (best guess as to where is in the mdx-scopes loader).

![image](https://user-images.githubusercontent.com/551247/51559633-4586af80-1e37-11e9-832d-88d392dd3cd6.png)

**Comment by jonnybot0** [comment] 2019-01-22 19:57
@ChristopherBiscardi - dang, you're right.

Trouble is, I'm still getting the same problem in my real site, even after deleting the .cache folder.

It's hard to reproduce a trivial example. I'm layering on _a lot_ (typescript, the experimental gatsby themes), and that may be part of the complexity. And yes, I did delete the .cache folder in both my site and my theme.

My custom component is called `DocImage`. It comes from a project that my site is pulling in using a custom webpack configuration. In my theme, I've got a slightly more complex layout for MDX pages called DefaultLayout.

![screen shot 2019-01-22 at 1 47 30 pm](https://user-images.githubusercontent.com/3723592/51561306-7cb38b80-1e4c-11e9-991d-94f87540704d.png)

Full error text from the browser console:
```
ReferenceError: DocImage is not defined[Learn More] commons.js line 1320 > Function:112:1
The above error occurred in the <MDXContent> component:
    in MDXContent
    in Unknown
    in Unknown
    in Unknown (at DefaultLayout.tsx:60)
    in div (at DefaultLayout.tsx:59)
    in main (at DefaultLayout.tsx:54)
    in MDXProvider (at DefaultLayout.tsx:43)
    in DefaultLayout (created by HotExportedDefaultLayout)
    in AppContainer (created by HotExportedDefaultLayout)
    in HotExportedDefaultLayout (created by PageRenderer)
    in PageRenderer (created by JSONStore)
    in JSONStore (created by EnsureResources)
    in ScrollContext (created by EnsureResources)
    in RouteUpdates (created by EnsureResources)
    in EnsureResources (created by RouteHandler)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by Root)
    in Root
    in MDXScopeProvider
    in _default

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer. index.js:2177
ReferenceError: "DocImage is not defined"
	render http://localhost:8000/commons.js line 1320 > Function:112:1
	finishClassComponent http://localhost:8000/commons.js:45232:22
	updateClassComponent http://localhost:8000/commons.js:45187:24
	beginWork http://localhost:8000/commons.js:46033:16
	performUnitOfWork http://localhost:8000/commons.js:48848:12
	workLoop http://localhost:8000/commons.js:48888:24
	renderRoot http://localhost:8000/commons.js:48974:7
	performWorkOnRoot http://localhost:8000/commons.js:49863:7
	performWork http://localhost:8000/commons.js:49775:7
	performSyncWork http://localhost:8000/commons.js:49749:3
	requestWork http://localhost:8000/commons.js:49618:5
	scheduleWork http://localhost:8000/commons.js:49427:5
	scheduleRootUpdate http://localhost:8000/commons.js:50095:3
	updateContainerAtExpirationTime http://localhost:8000/commons.js:50123:10
	updateContainer http://localhost:8000/commons.js:50180:10
	render http://localhost:8000/commons.js:50472:3
	legacyRenderSubtreeIntoContainer http://localhost:8000/commons.js:50612:9
	unbatchedUpdates http://localhost:8000/commons.js:49978:10
	legacyRenderSubtreeIntoContainer http://localhost:8000/commons.js:50608:5
	render http://localhost:8000/commons.js:50669:12
	js http://localhost:8000/commons.js:16640:7
```

I'm going to hack around with it a bit more to see if I can get to the bottom of it, but if anyone has any pointers I'd be much obliged.

**Comment by ChristopherBiscardi** [comment] 2019-01-22 20:04
@jonnybot0 I'm happy to take a look at the full site if you're able to make it available to me. The interaction between Themes, MDX, and TypeScript is something I'd be interested in digging into (since I'm currently responsible for two of those layers haha).

If you run the site with the debug flags enabled for gatsby you may get some more information too.

```
DEBUG=gatsby* yarn develop
```

**Comment by jonnybot0** [comment] 2019-01-22 20:16
Well *hello* there, tall, dark, and verbose!

```
success run graphql queries — 1.529 s — 8/8 5.24 queries/second
success write out page data — 0.004 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s
  gatsby:html generating static HTML +0ms
  gatsby:webpack-config Loading webpack config for stage "develop-html" +0ms
  gatsby:webpack-config Building env for "develop-html" +9ms
  gatsby:webpack-config Error resolving user loaders directory { Error: ENOENT: no such file or directory, stat '/Users/jonny/myProject/loaders'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/jonny/myProject/node_modules/graceful-fs/polyfills.js:295:24)
    at statSync (/Users/jonny/myProject/node_modules/gatsby/src/utils/webpack.config.js:392:14)
    at getResolveLoader (/Users/jonny/myProject/node_modules/gatsby/src/utils/webpack.config.js:427:20)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jonny/myProject/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/jonny/myProject/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at tryCatcher (/Users/jonny/myProject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/jonny/myProject/loaders' } +1ms
(node:8753) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
  gatsby:webpack-config Loading webpack config for stage "develop" +18s
  gatsby:webpack-eslint-config Attempting to load package.json for eslint config check +0ms
  gatsby:webpack-eslint-config Checking for eslint config file +0ms
  gatsby:webpack-config Building env for "develop" +19ms
  gatsby:webpack-config Error resolving user loaders directory { Error: ENOENT: no such file or directory, stat '/Users/jonny/myProject/loaders'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/jonny/myProject/node_modules/graceful-fs/polyfills.js:295:24)
    at statSync (/Users/jonny/myProject/node_modules/gatsby/src/utils/webpack.config.js:392:14)
    at getResolveLoader (/Users/jonny/myProject/node_modules/gatsby/src/utils/webpack.config.js:427:20)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jonny/myProject/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/jonny/myProject/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at tryCatcher (/Users/jonny/myProject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/jonny/myProject/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/jonny/myProject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/jonny/myProject/loaders' } +2ms
 DONE  Compiled successfully in 16770ms     
```

Not 100% sure what that means yet, but it's something to investigate.

Thanks for the debug tip! I'd love to share my repo with you as an example, but I'd have to make a somewhat obfuscated copy first. Basically, I'm trying to pull components from my actual app (which can't be a static site) into a static gatsby site for the documentation. To get a shareable example, I'd need to disentangle it from my app's source, which I really ought not to share. :)

Thanks for your characteristic willingness to dive and help.

**Comment by jonnybot0** [comment] 2019-01-22 21:36
So, the problem seems to be that my consumer site sets a custom webpack config that defines [an alias](https://webpack.js.org/configuration/resolve/#resolve-alias) from which my custom component can be resolved. I know that the alias is basically good.

My MDX files get loaded and parsed by `gatsby-mdx` from a separate directory next to my consumer site using `gatsby-source-filesystem`. 

`gatsby-mdx` boils the MDX body down to code like this:

```
class MDXContent extends React.Component {
    constructor(props) {
        super(props);
        this.layout = null;
    }

    render() {
        const _this$props = this.props,
            {
                components
            } = _this$props,
            props = _objectWithoutProperties(_this$props, ["components"]);

        return React.createElement(MDXTag, { name: "wrapper", components: components },
            React.createElement(MDXTag, {
                name: "h1",
                components: components
            }, `Lorem ipsum`),

            React.createElement(MDXTag, {
                name: "p",
                components: components
            }, `Dolor`),
            `Plain text child`,

            React.createElement(MyCustomComponent, {
                propA: "Something something",
                probB: "Daaaark siiiiiiide"
            })
        );
    }
}
```

The trouble is, it doesn't seem to be including the imports that I suspect React needs in order to render my custom component (e.g. https://github.com/mdx-js/mdx/issues/197#issuecomment-407812337).

Likewise, nothing I pass to the MDXProvider is likely to matter, since the generated code isn't invoking MDXTag (which is what causes MDXProvider's components to get consumed, I believe). React itself has to know about my custom component, and for some reason it doesn't.

If I do this in a standalone site, such as the example I shared earlier, React still seems able to resolve my component. It's only when the site consuming a theme provides the component that the theme is meant to use in rendering MDX that I seem to have trouble.

**Comment by jonnybot0** [comment] 2019-01-22 21:57
I can even see that my custom component is properly included in the index.js file that gets generated. It's as though the MDXRenderer masks the greater react/webpack context.

**Comment by jonnybot0** [comment] 2019-01-24 16:24
As near as I can tell, something I'm doing when creating the pages programmatically is interfering with their interaction with the contents of the mdx-scopes directory. Those scope files are getting created correctly, but somehow the MDXRenderer doesn't pull them in... still a bit flummoxed, but digging through the source of gatsby-mdx and its example sites to see if I can't make heads or tails of it.

**Comment by jonnybot0** [comment] 2019-01-24 16:59
Adding the scope prop that brings in the scopeContexts loader fixes my issue. See above PR for my proposed change to the docs.

Very open to being told I'm doing it wrong, but this seems like the right fix, unless it's more appropriate to change the MDXRenderer component itself.

**Comment by ChristopherBiscardi** [comment] 2019-01-24 22:39
First off, thanks for the PR. The effort is much appreciated.

The `scope` prop isn't something you should have to use manually. It's there as an override mechanism or for more special use cases. It should be documented, but also called out as "not the way you should need to do things". The `mdx-scopes` loader specifically is something that definitely shouldn't be relied on (and thus should *not* be documented). It's an implementation detail for gatsby-mdx internals and it imports the entire combined scope across all MDX files.

> It's only when the site consuming a theme provides the component that the theme is meant to use in rendering MDX that I seem to have trouble.

This is useful, but it's really hard to know what your setup is without being able to reproduce it. Is there any way I could get the site to run it and experience the error? I have themes that are using MDX and work well, so I'm more guessing this is a typescript issue. I'm marking this as "needs reproduction" because the original issue was a .cache issue and the issue in your real site is apparently something else.

> The trouble is, it doesn't seem to be including the imports that I suspect React needs in order to render my custom component

yeah, this is how gatsby-mdx works. It splits off the imports so webpack can know about and bundle them, then ships the code body down when you query it through GraphQL and we re-attach the imports through context that provides the scope. This code body is "as expected" so the problem is somewhere else, like the way typescript is compiling your files for example.

**Comment by jonnybot0** [comment] 2019-01-24 23:22
Thanks very much, @ChristopherBiscardi. I'd like to see about getting an example repo together that can reproduce the problem, but likely won't have time for the forseeable future (i.e. next week or so). I'll post on here if/when I do.

**Comment by snawbel** [comment] 2019-01-27 11:10
My problems were due to using the `scope` prop of `MdxRenderer`. When I started using the `globalScope` option instead, importing components in the mdx file started working.

**Comment by ChristopherBiscardi** [comment] 2019-01-30 19:37
Going to close this until a repro is available. Happy to re-open when there is.

**Closed by ChristopherBiscardi** 2019-01-30 19:37 UTC
Labels: needs-reproduction
