### ISSUE TITLE
Warning "Unsupported style property" when using gatsby-remark-images

### ISSUE THREAD

**Issue by gabefromutah** [ChristopherBiscardi/gatsby-mdx#198] opened 2018-12-03 23:13 UTC
**Describe the bug**
Warning `Unsupported style property...` when embedding images using `gatsby-remark-images`. This seems to impact the nice rendering experience that `gatsby-remark-images` offers. I would love to contribute and help out with this if you can point me in the right direction. 

**To Reproduce**
1. Run the docs example using `gatsby develop`
2. Navigate to http://localhost:8000/guides/using-gatsby-remark-images
3. Open the console and see warnings.

**Expected behavior**
I expect to see no warnings in console. In the browser, I expect to see a base64 encoded fuzzy image with appropriate image dimensions followed by the load of the higher resolution image.

**Screenshots**
![dec-03-2018 15-12-00](https://user-images.githubusercontent.com/32469058/49407554-d2ea3500-f70d-11e8-9c90-f037a70beead.gif)

![image](https://user-images.githubusercontent.com/32469058/49407450-86065e80-f70d-11e8-9cfe-35a01a28919a.png)
![image](https://user-images.githubusercontent.com/32469058/49407456-8dc60300-f70d-11e8-9385-d6383240ecc5.png)

**Comment by ChristopherBiscardi** [comment] 2018-12-04 06:19
What version of gatsby-mdx are you on?

---

This is sort of a continuing problem with the html-to-jsx conversion. I'm attempting to fix it in #190, but would appreciate any help.

Basically the problem is that when you write MDX files, it expects all the HTML you would normally write in a Markdown file to be JSX. This is fine for manually authoring MDX because you can just modify your HTML a bit and the HTML people write in Markdown is usually simple enough to pass for JSX anyway. The problem comes in when applying `gatsby-remark-*` plugins. The gatsby plugins have free reign to modify the AST and insert HTML wherever they want. MDX doesn't have a process for converting HTML content to JSX at the end of applying the plugins so it comes out as JSX, but with HTML attributes.

We need a way to convert the HTML that the gatsby-remark-* plugins produce to JSX, without harming any existing JSX in the MDX document. This is why we have the [html-to-jsx plugin](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/efd60444655d3cd83af12f419a6e211f6b2ec553/packages/gatsby-mdx/utils/get-source-plugins-as-remark-plugins.js#L20). Unfortunately the html to jsx implementation we've been using isn't well maintained so we've had to fork it a bit which isn't helping either.

So that's the long version of what's going on. Our options are basically do the html-to-jsx conversion well or fork the gatsby-remark-images, etc plugins (which sounds like a bad idea). I just haven't had time to write out a full html-to-jsx conversion tool and I haven't found one that suits our needs.

**Comment by gabeskipio** [comment] 2018-12-04 16:08
To answer your question, I believe i was on the lastest version of master efd60444655d3cd83af12f419a6e211f6b2ec553. 

Thanks for the explanation, I'll poke around a bit to see if I can get https://github.com/ChristopherBiscardi/gatsby-mdx/pull/190 any closer.

**Comment by ChristopherBiscardi** [comment] 2018-12-06 01:43
Latest master, interesting. So you're using a ci build or building it yourself?

**Comment by johno** [comment] 2019-01-29 20:04
This should be fixed on the latest version.

**Closed by johno** 2019-01-29 20:04 UTC
