### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by johncmunson** [ChristopherBiscardi/gatsby-mdx#152] opened 2018-09-25 19:07 UTC
**Describe the bug**
Attempting to reference images with .mdx files, as described in the guide "Using Gatsby Remark Images", throws an error... `TypeError: Cannot read property 'parent' of undefined`

**To Reproduce**
1. `git clone https://github.com/gatsby-mdx-starter/gatsby-mdx-starter/tree/gatsby-remark-images`
2. `npm install`
3. `gatsby develop`

**Expected behavior**
Running `gatsby develop` should not throw any errors

**Screenshots**
![screen shot 2018-09-25 at 2 00 16 pm](https://user-images.githubusercontent.com/19480078/46036806-18660280-c0cc-11e8-8eb9-c6e17d423eea.jpg)

**Comment by ChristopherBiscardi** [comment] 2018-09-26 09:28
hey, I checked out the repo but I don't get this error on `gatsby develop`. I did see that the using images was referencing the [wrong filepath](https://github.com/gatsby-mdx-starter/gatsby-mdx-starter/pull/1) for the image so I fixed that and the image shows up now.

I'm going to close this since the repo doesn't seem to reproduce the `parent` problem. Was this perhaps related to #154 and the filesystem source which I see was added by now? If you still see this issue pop up, `@` me here and I'll re-open if you have a repro case.

**Closed by ChristopherBiscardi** 2018-09-26 09:28 UTC
