### ISSUE TITLE
 Process hangs before compiling after a file change

### ISSUE THREAD

**Issue by jonsuh** [ChristopherBiscardi/gatsby-mdx#175] opened 2018-10-13 00:17 UTC
After running `gatsby develop`, when I make a changes to one of the posts, it detects that a file has changed, but hangs for `10`–`30` seconds before the compile happens (the compile itself is quick, though).

```
info changed file at /gatsby/src/blog/2018/animated-toggle-react-native/index.mdx

<!-- The process hangs for 10–30 seconds... -->

ℹ ｢wdm｣: Compiling...
 DONE  Compiled successfully in 237ms

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
```

The process only hangs for blog posts (there are about 80), which are in `src/blog/*`. `.mdx` files in `src/pages/*` regenerate almost immediately.

**Question:** Is this a known/expected issue? Anyone else experience the same?

If not, curious if anyone has an idea what could be causing it or know a way to debug to determine the cause.

## More details

There are the plugins I’m using:
```
module.exports = {
  plugins: [
    {
      resolve: "gatsby-mdx",
      options: {
        gatsbyRemarkPlugins: [
          { resolve: "gatsby-remark-autolink-headers" },
          {
            resolve: "gatsby-remark-copy-linked-files",
            options: {
              relativeDirs: true,
              ignoreFileExtensions: [],
            },
          },
          { resolve: "gatsby-remark-prismjs" },
        ],
      },
    },
    "gatsby-plugin-react-helmet",
    {
      resolve: "gatsby-plugin-sass",
      options: {},
    },
    "gatsby-plugin-react-svg",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "blog",
        path: `${__dirname}/src/blog`,
      },
    },
    "gatsby-plugin-offline",
  ],
}
```

For files in `src/blog/` I’m generating pages via `exports.createPages()`, like this:

```
exports.createPages = ({ actions, graphql }) => {
  const { createPage } = actions

  return graphql(`
    {
      posts: allMdx(
        filter: { frontmatter: { hidden : { ne: true } } }
        sort: { order: DESC, fields: [frontmatter___date] }
        limit: 200
      )
      {
        edges {
          node {
            id
            excerpt
            code {
              body
              scope
            }
            fields {
              dir
              path
              slug
            }
            frontmatter {
              date
              excerpt
              title
            }
          }
        }
      }
    }
  `).then(result => {
    if (result.errors) {
      return Promise.reject(result.errors)
    }

    createPaginatedPages({
      edges: result.data.posts.edges,
      createPage: createPage,
      pageTemplate: "src/templates/blog-index.js",
      pathPrefix: "blog",
      buildPath: (index, pathPrefix) => index > 1 ? `${pathPrefix}/page/${index}` : `/${pathPrefix}`,
      context: {},
    })

    const posts = result.data.posts.edges

    _.each(posts, (post, index) => {
      const previous = index === posts.length - 1 ? null : posts[index + 1].node
      const next = index === 0 ? null : posts[index - 1].node

      createPage({
        path: `${post.node.fields.path}`,
        component: componentWithMDXScope(
          path.resolve("./src/templates/blog-post.js"),
          post.node.code.scope,
          __dirname,
        ),
        context: {
          slug: post.node.fields.slug,
          previous,
          next,
        },
      })
    })
  })
}
```

And `blog-post.js` template looks like the following:
```
class BlogPostPage extends React.Component {
  render() {
    const { mdx } = this.props.data
    const { frontmatter } = this.props.data.mdx

    return (
      <Layout>
        <h1>{frontmatter.title}</h1>
        <MDXRenderer scope={this.props.__mdxScope}>
          {mdx.code.body}
        </MDXRenderer>
      </Layout>
    )
  }
}
```

**Comment by jonsuh** [comment] 2018-10-13 00:28
I’ve also tried the following, but they didn’t help:

- Removing all plugins from `gatsbyRemarkPlugins`.
- Removing all other pages from `createPages()` so I’m _only_ generating blog posts (I was generating pages for pagination, hidden posts, tags, and categories)

**Comment by ChristopherBiscardi** [comment] 2018-10-13 19:44
We aren't doing any interesting caching yet, so I could see us being a bit slow at some as-yet-undetermined number of mdx posts.

Does the repo happen to be open source? Otherwise I'll work on a reproduction of the performance issue and  see if we can introduce caching to improve speed.

**Comment by ChristopherBiscardi** [comment] 2018-12-31 16:19
Closing since we don't have a repro case and a lot has changed

**Closed by ChristopherBiscardi** 2018-12-31 16:19 UTC
