### ISSUE TITLE
Use gatsby-remark-images with react-slick inside MDX files

### ISSUE THREAD

**Issue by nestarz** [ChristopherBiscardi/gatsby-mdx#182] opened 2018-10-22 22:08 UTC
**Describe the bug**
Can't wrap gatsby-remark-images inside React Components. It ignore plugins like gatsby-remark-images and can't find the file.

**To Reproduce**

page.mdx
```
# Introduction

import Slider from "react-slick";

export const settings = {
      focusOnSelect: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      speed: 500
    };

<Slider {...settings}>
    <div>
    <img src={"final7.png"}/> /* Do not Works */
    </div>
    <div>
    <img src={"final8.png"}/>  /* Do not Works */
    </div>
</Slider>

<img src="final7.png"/> /* Works */
![my image](./final7.png) /* Works */

```

**Expected behavior**
A carousel with gatsby-remark-images processed images

**Comment by ChristopherBiscardi** [comment] 2019-01-30 19:21
dupe of https://github.com/ChristopherBiscardi/gatsby-mdx/issues/251

**Closed by ChristopherBiscardi** 2019-01-30 19:21 UTC
