### ISSUE TITLE
gatsby-mdx async issues?

### ISSUE THREAD

**Issue by eddnav** [ChristopherBiscardi/gatsby-mdx#174] opened 2018-10-12 20:32 UTC
I'm trying to get gatsby-mdx to work with an existing project, however I can't seem to even be able to add the plugin:

````
eddnav$ gatsby develop
success open and validate gatsby-config — 0.007 s
success load plugins — 0.265 s
error Plugin gatsby-mdx returned an error


  Error: /Users/eddnav/Projects/Web/abtoxy/node_modules/gatsby-mdx/gatsby/on-cre  ate-node.js:4
  module.exports = async (
                         ^
  SyntaxError: Unexpected token (
````

These are my versions:
````
dependencies": {
    "@mdx-js/mdx": "^0.15.5",
    "@mdx-js/tag": "^0.15.0",
    "gatsby": "^2.0.19",
    "gatsby-mdx": "^0.2.0",
````

Is this maybe a Babel related issue?

**Comment by silvenon** [comment] 2018-10-13 10:27
What is your Node version? You might need 7.10.1 or greater.

**Comment by eddnav** [comment] 2018-10-14 19:49
That did the trick, however, I think I might've found a similar issue after finally getting `gatsby develop` to work, this error happens after a `gatsby build` too: 
````
VM2468:3 Uncaught SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at __webpack_exports__.default.Object (Users/eddnav/Projects/Web/abtoxy/node_modules/gatsby-mdx/mdx-renderer.js:20)
    at ProxyFacade (Users/eddnav/Projects/Web/abtoxy/node_modules/react-hot-loader/dist/react-hot-loader.development.js:675)
    at mountIndeterminateComponent (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:13744)
    at beginWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:14068)
    at performUnitOfWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:16415)
    at workLoop (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:16453)
    at HTMLUnknownElement.callCallback (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:145)
    at Object.invokeGuardedCallbackDev (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:195)
    at invokeGuardedCallback (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:248)
    at replayUnitOfWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:15744)
    at renderRoot (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:16547)
    at performWorkOnRoot (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17386)
    at performWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17294)
    at performSyncWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17266)
    at requestWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17154)
    at scheduleWork (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:16948)
    at scheduleRootUpdate (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17636)
    at updateContainerAtExpirationTime (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17663)
    at updateContainer (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17690)
    at ReactRoot.render (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17956)
    at eval (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:18096)
    at unbatchedUpdates (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:17517)
    at legacyRenderSubtreeIntoContainer (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:18092)
    at render (Users/eddnav/Projects/Web/abtoxy/node_modules/react-dom/cjs/react-dom.development.js:18151)
    at eval (Users/eddnav/Projects/Web/abtoxy/.cache/app.js:98)
````
I'm not very familiar with Webpack, so this might also be a problem with that. 

My Node version atm is: `10.11.0`

**Comment by silvenon** [comment] 2018-10-14 20:08
Hm, template literals are very well supported. Could you isolate this error into a repository? It's hard to investigate this way.

**Comment by ChristopherBiscardi** [comment] 2018-10-15 03:37
@eddnav you should be able to fork https://github.com/ChristopherBiscardi/gatsby-mdx-minimal-repro to create a minimal reproduction easily. First check if the raw repo causes issues for you, then add what you think might be causing the problem until it breaks.

**Comment by ChristopherBiscardi** [comment] 2018-11-08 06:33
Closing this since we don't have a repro and I suspect the issue isn't in MDXRenderer. Happy to reopen if there's a repro using the reproduction repo.

**Closed by ChristopherBiscardi** 2018-11-08 06:33 UTC
